# Generated by Django 4.1.7 on 2023-03-19 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='MIC code')),
                ('name', models.CharField(max_length=15, verbose_name='Name of Stock Exchange')),
                ('country', models.CharField(max_length=25, verbose_name='Country')),
                ('timezone', models.CharField(max_length=35, verbose_name='TimeZone')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Symbol')),
                ('name', models.CharField(max_length=200, verbose_name='Name of Stock')),
                ('currency', models.CharField(max_length=3, verbose_name='Market Currency')),
                ('stock_type', models.CharField(max_length=30, verbose_name='Stock Type')),
                ('mic_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.exchange')),
            ],
        ),
    ]
