# Generated by Django 4.1.7 on 2023-03-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, verbose_name='Symbol')),
                ('name', models.CharField(max_length=200, verbose_name='Name of Stock')),
                ('currency', models.CharField(max_length=3, verbose_name='Market Currency')),
                ('stock_type', models.CharField(max_length=30, verbose_name='Stock Type')),
                ('mic_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='api.exchange')),
            ],
            options={
                'unique_together': {('symbol', 'mic_code')},
            },
        ),
    ]
